[tool.poetry]
name = "effective-mobile"
version = "0.1.0"
description = ""
authors = ["Aleksey Melnikov <mas-chel@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
rapidfuzz = "^3.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
